CREATE DATABASE Smart_Clinic;

CREATE TABLE ROLES(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME_ROLES NVARCHAR(400),);

CREATE TABLE USERS(
ID INT PRIMARY KEY IDENTITY(1,1),
FULL_NAME NVARCHAR(400),
EMAIL NVARCHAR(400) NOT NULL,
PASSWORDHASH NVARCHAR(400),
PHONE NVARCHAR(100) NOT NULL,
CreatedAt DATE,
IsActive BIT,
ROLES_ID_USERS INT,
FOREIGN KEY (ROLES_ID_USERS) REFERENCES ROLES(ID));

CREATE TABLE Doctors(
ID INT PRIMARY KEY IDENTITY(1,1),
Biography NVARCHAR(500),
YEARS_OF_EXPERIENCE INT,
Consultationlnfo NVARCHAR(MAX),
Imagepath NVARCHAR(400),
IsActive BIT,
ID_USER_DOCTORS INT,
FOREIGN KEY (ID_USER_DOCTORS) REFERENCES USERS (ID));

CREATE TABLE PATIENS(
ID INT PRIMARY KEY IDENTITY(1,1),
DATA_OF_BIRTH DATE,
GENDER NVARCHAR(150),
IMAGE_PATH NVARCHAR(500),
ID_USERS_PATIEN INT,
FOREIGN KEY (ID_USERS_PATIEN) REFERENCES USERS(ID));

CREATE TABLE Specialties(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME NVARCHAR(400),
Description NVARCHAR(MAX),
IconOrImagePath NVARCHAR(MAX),
ISACTIVE BIT,
DoctorSpecialties INT,
FOREIGN KEY (DoctorSpecialties) REFERENCES Doctors(ID));

CREATE TABLE Appointments(
ID INT PRIMARY KEY IDENTITY(1,1),
AppointmentDate DATE,
AppointmentTime TIME,
NOTSE NVARCHAR(MAX),
Status NVARCHAR(MAX),
CreatedAt DATE,
UPDATEDAT NVARCHAR(MAX),
Patient_ld_Appointments INT,
FOREIGN KEY (Patient_ld_Appointments) REFERENCES PATIENS(ID),
Doctor_ld_Appointments INT,
FOREIGN KEY(Doctor_ld_Appointments) REFERENCES Doctors(ID));

CREATE TABLE DOCTOR_SCHOEDULES(
ID INT PRIMARY KEY IDENTITY(1,1),
AvailableDate DATE ,
StartTime TIME,
EndTime TIME,
SlotMinutes TIME,
IsAvaiIabIe BIT,
Doctor_ld_SCHOEDULES INT,
FOREIGN KEY (Doctor_ld_SCHOEDULES) REFERENCES Doctors(ID));

CREATE TABLE Services(
ID INT PRIMARY KEY IDENTITY(1,1),
Title NVARCHAR(MAX), 
Description NVARCHAR(MAX),
rconOrTmagePath NVARCHAR(MAX),
DisplayOrder NVARCHAR(350));

CREATE TABLE Testimonials(
ID INT PRIMARY KEY IDENTITY(1,1),
PatientName NVARCHAR(MAX),
MASSAGE NVARCHAR(MAX),
RATING INT,
ImagePath NVARCHAR(MAX),
ISVisibIe BIT);

CREATE TABLE CONTACTMESSAGE(
ID INT PRIMARY KEY IDENTITY(1,1),
FULL_NAME NVARCHAR(MAX),
EMAIL NVARCHAR(300),
SUBJACT NVARCHAR(MAX),
MASSAGE NVARCHAR(MAX),
ISREAD BIT,
CreatedAt DATE);

CREATE TABLE WEBSITSETTING(
ID INT PRIMARY KEY IDENTITY(1,1),
ClinicName NVARCHAR(400),
HeroTitIe NVARCHAR(300),
HeroText NVARCHAR(MAX),
AboutText NVARCHAR(300),
Address NVARCHAR(350),
PHONE INT NOT NULL,
EMAIL NVARCHAR(300),
WorkingHours TIME NOT NULL);

